stages:
#  - test
  - build
  - push

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  LATEST_TAG: $CI_REGISTRY_IMAGE:latest

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY"

#lint_and_test:
#  # Use a Node.js image to run npm commands
#  image: node:18
#  stage: test
#  only:
#    - merge_request
#  script:
#    - npm install
#    - npm run lint
#    - npm run test

build_image:
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
    - docker tag $IMAGE_TAG $LATEST_TAG
  only:
    - main  # Specify the branch that should trigger the build
    - merge_requests

push_image:
  stage: push
  script:
    - docker push $IMAGE_TAG
    - docker push $LATEST_TAG
  only:
    - main