image: docker:latest

services:
  - docker:dind

stages:
  - version
  - build

variables:
  DOCKER_DRIVER: overlay2

#lint_and_test:
#  # Use a Node.js image to run npm commands
#  image: node:18
#  stage: test
#  only:
#    - merge_request
#  script:
#    - npm install
#    - npm run lint
#    - npm run test


# Job to increment the version on merge to master
update_version:
  stage: version
  script:
    - if [ "$CI_COMMIT_BRANCH" == "master" ]; then
        echo "Updating version...";
        current_version=$(cat $VERSION_FILE);
        IFS='.' read -r -a version_parts <<< "$current_version";
        last_part=$((version_parts[2] + 1));
        new_version="${version_parts[0]}.${version_parts[1]}.$last_part";
        if [ $last_part -gt 99 ]; then
          version_parts[1]=$((version_parts[1] + 1));
          last_part=0;
          new_version="${version_parts[0]}.${version_parts[1]}.$last_part";
        fi;
        if [ ${version_parts[1]} -gt 99 ]; then
          version_parts[0]=$((version_parts[0] + 1));
          version_parts[1]=0;
          new_version="${version_parts[0]}.${version_parts[1]}.0";
        fi;
        echo $new_version > $VERSION_FILE;
        git config --global user.email "ci@example.com";
        git config --global user.name "CI Bot";
        git add $VERSION_FILE;
        git commit -m "Bump version to $new_version";
        git tag "v$new_version";
        git push origin master --tags;
      fi
  only:
    - master

build_image:
  stage: build
  before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - version=$(cat .version)
    - docker build -t $CI_REGISTRY_IMAGE:$version .
    - docker tag $CI_REGISTRY_IMAGE:$version $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$version
  only:
    - master